import { withoutEmDashes } from '@/lib/typography';
type Enrichment = { title?: string; description?: string; city?: string; department?: string; address?: string; location?: string; website?: string; phone?: string; sources?: Array<{ url: string; title?: string; checkedAt: string }>; missing: string[] };
const clean = (v: unknown, max = 1000) => typeof v === 'string' ? withoutEmDashes(v.trim().slice(0, max)) : '';
export async function enrichMosque(input: Record<string, unknown>): Promise<Enrichment | null> {
  const key = process.env.GEMINI_API_KEY; const query = [input.title, input.city, input.address, input.postal, input.department].filter(Boolean).join(', '); if (!key || !query) return null;
  const prompt = `Recherche factuelle sur cet établissement musulman en France: ${query}. Utilise Google Search et recoupe les sources. Ne déduis rien. JSON uniquement: title, description, city, department, address, location, website HTTPS officiel, phone, sources [{url,title}], missing []. Si le nom générique Mosquée est la seule information certaine, laisse title vide et ajoute nom officiel à missing.`;
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ role: 'user', parts: [{ text: prompt }] }], tools: [{ google_search: {} }], generationConfig: { temperature: 0, responseMimeType: 'application/json', maxOutputTokens: 1800 } }), signal: AbortSignal.timeout(30000) });
  if (!response.ok) return null;
  try { const data = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> }; const p = JSON.parse(data.candidates?.[0]?.content?.parts?.[0]?.text || '{}') as Record<string, unknown>; const sources = Array.isArray(p.sources) ? p.sources.filter((s): s is Record<string, unknown> => !!s && typeof s === 'object').map(s => ({ url: clean(s.url), title: clean(s.title, 200), checkedAt: new Date().toISOString() })).filter(s => /^https:\/\//.test(s.url)) : []; const result: Enrichment = { title: clean(p.title, 240), description: clean(p.description, 3000), city: clean(p.city, 120), department: clean(p.department, 3), address: clean(p.address, 300), location: clean(p.location, 240), website: clean(p.website), phone: clean(p.phone, 80), sources, missing: Array.isArray(p.missing) ? p.missing.map(String).slice(0, 12) : [] }; if (!result.title || result.title.toLocaleLowerCase('fr-FR') === 'mosquée') result.missing.push('nom officiel'); if (!result.address) result.missing.push('adresse complète'); if (!sources.length) result.missing.push('source HTTPS vérifiable'); return result; } catch { return null; }
}
