'use client';
import { useEffect, useMemo, useState } from 'react';

type Lead = { id: string; name: string; email: string; phone?: string | null; travelType: string; offerId: string | null; status: string; qualification?: Record<string, unknown> | null; createdAt: string };
const statuses = ['new','qualified','assigned','accepted','quoted','won','lost','expired'];
const statusLabels: Record<string, string> = { new: 'Nouveau', qualified: 'Qualifié', assigned: 'Attribué', accepted: 'Pris en charge', quoted: 'Devis demandé', won: 'Finalisé', lost: 'Sans suite', expired: 'Archivé' };

export default function LeadsClient() {
 const [leads, setLeads] = useState<Lead[]>([]); const [selected, setSelected] = useState<Lead | null>(null); const [loading, setLoading] = useState(true);
 async function load() { setLoading(true); const r = await fetch('/api/admin/leads'); const j = await r.json(); setLeads(j.leads ?? []); setSelected(current => current ? (j.leads ?? []).find((lead: Lead) => lead.id === current.id) ?? null : null); setLoading(false); }
 useEffect(() => { load(); }, []);
 async function change(id: string, status: string) { await fetch('/api/admin/leads', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); await load(); }
 const template = useMemo(() => { if (!selected) return ''; const q = selected.qualification || {}; return `Bonjour,\n\nNous vous contactons au sujet d'une demande de ${selected.travelType} déposée sur Al-Wasil.\n\nClient : ${selected.name}\nBudget : ${String(q.budget || q.budget_max || 'non précisé')}\nPériode : ${String(q.periode || q.date || 'non précisée')}\nDépart : ${String(q.depart || q.ville_depart || 'non précisé')}\nVoyageurs : ${String(q.voyageurs || q.nombre || 'non précisé')}\nDétails : ${String(q.message || q.details || 'aucun')}\n\nPouvez-vous proposer une formule adaptée et confirmer les conditions, les dates et les éléments inclus ?\n\nCordialement,\nMégane\nAl-Wasil\nmegane@al-wasil.fr`; }, [selected]);
 if (loading) return <p>Chargement des demandes…</p>;
 return <div style={{ display: 'grid', gridTemplateColumns: 'minmax(250px, .9fr) minmax(360px, 1.4fr)', gap: '1rem', alignItems: 'start' }}><section style={{ display: 'grid', gap: '.6rem' }}>{leads.map(lead => <button key={lead.id} onClick={() => setSelected(lead)} style={{ textAlign: 'left', background: selected?.id === lead.id ? '#f0ebfa' : 'white', border: selected?.id === lead.id ? '2px solid #7652CA' : '1px solid #ead9a6', borderRadius: 10, padding: '.85rem', cursor: 'pointer' }}><strong>{lead.name}</strong><div style={{ fontSize: '.78rem', color: '#59565f' }}>{lead.travelType} · {statusLabels[lead.status] || lead.status}</div><div style={{ fontSize: '.7rem', color: '#a8a29e' }}>{new Date(lead.createdAt).toLocaleString('fr-FR')}</div></button>)}</section><section style={{ background: 'white', border: '1px solid #ead9a6', borderRadius: 12, padding: '1.25rem', minHeight: 300 }}>{!selected ? <p style={{ color: '#6b7280' }}>Sélectionne une demande pour voir le ticket.</p> : <><h2 style={{ margin: 0 }}>{selected.name}</h2><p style={{ color: '#59565f' }}>{selected.email}{selected.phone ? ` · ${selected.phone}` : ''}</p><div style={{ display: 'grid', gap: '.35rem', margin: '1rem 0' }}>{Object.entries(selected.qualification || {}).map(([key, value]) => <div key={key} style={{ fontSize: '.85rem' }}><strong>{key} :</strong> {String(value)}</div>)}</div><label style={{ display: 'block', fontWeight: 700, fontSize: '.8rem' }}>Statut<select value={selected.status} onChange={e => change(selected.id, e.target.value)} style={{ display: 'block', width: '100%', padding: '.55rem', marginTop: '.35rem' }}>{statuses.map(status => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></label><h3 style={{ marginBottom: '.4rem' }}>Message prêt à envoyer à l’agence</h3><textarea value={template} readOnly rows={12} style={{ width: '100%', boxSizing: 'border-box', padding: '.75rem', border: '1px solid #ddd6fe', borderRadius: 8, fontFamily: 'inherit' }} /><a href={`mailto:?subject=${encodeURIComponent(`Demande ${selected.travelType} - ${selected.name}`)}&body=${encodeURIComponent(template)}`} style={{ display: 'inline-block', marginTop: '.65rem', background: '#7652CA', color: 'white', borderRadius: 8, padding: '.65rem 1rem', fontWeight: 700, textDecoration: 'none' }}>Ouvrir le mail prérempli</a></>}</section></div>;
}
