'use client';

import { useEffect, useMemo, useState } from 'react';

type LeadEvent = { id: string; event: string; actor: string; createdAt: string };
type Lead = { id: string; name: string; email: string; phone?: string | null; travelType: string; offerId: string | null; status: string; qualification?: Record<string, unknown> | null; createdAt: string; events?: LeadEvent[] };
const statuses = ['new', 'qualified', 'assigned', 'accepted', 'quoted', 'won', 'lost', 'expired'];
const statusLabels: Record<string, string> = { new: 'Nouveau', qualified: 'Qualifié', assigned: 'Attribué', accepted: 'Pris en charge', quoted: 'Devis demandé', won: 'Finalisé', lost: 'Sans suite', expired: 'Archivé' };

export default function LeadsClient() {
 const [leads, setLeads] = useState<Lead[]>([]); const [selected, setSelected] = useState<Lead | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState('');
 async function load() { setLoading(true); setLoadError(''); try { const response = await fetch('/api/admin/leads', { cache: 'no-store', signal: AbortSignal.timeout(8000) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Impossible de charger les demandes.'); const nextLeads = (data.leads || []) as Lead[]; setLeads(nextLeads); setSelected(current => current ? nextLeads.find(lead => lead.id === current.id) || null : null); } catch (error) { setLoadError(error instanceof Error ? error.message : 'Impossible de charger les demandes.'); } finally { setLoading(false); } }
 useEffect(() => { load(); }, []);
 async function change(id: string, status: string) { const response = await fetch('/api/admin/leads', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); setLoadError(data.error || 'Modification impossible.'); return; } await load(); }
 const template = useMemo(() => { if (!selected) return ''; const q = selected.qualification || {}; return `Bonjour,\n\nNous vous contactons au sujet d'une demande de ${selected.travelType} déposée sur Al-Wasil.\n\nClient : ${selected.name}\nBudget : ${String(q.budget || q.budget_max || 'non précisé')}\nPériode : ${String(q.periode || q.date || 'non précisée')}\nDépart : ${String(q.depart || q.ville_depart || 'non précisé')}\nVoyageurs : ${String(q.voyageurs || q.nombre || 'non précisé')}\nDétails : ${String(q.message || q.details || 'aucun')}\n\nPouvez-vous proposer une formule adaptée et confirmer les conditions, les dates et les éléments inclus ?\n\nCordialement,\nMégane\nAl-Wasil\nmegane@al-wasil.fr`; }, [selected]);
 if (loading) return <p>Chargement des demandes…</p>;
 if (loadError) return <div style={{ padding: '1rem', border: '1px solid #fecaca', borderRadius: 10, background: '#fff1f2', color: '#991b1b' }}><strong>Impossible de charger les tickets.</strong><p style={{ margin: '.4rem 0' }}>{loadError}</p><button onClick={load} style={{ padding: '.5rem .8rem', borderRadius: 8, border: 0, background: '#7652CA', color: 'white', fontWeight: 700 }}>Réessayer</button></div>;
 return <div style={{ display: 'grid', gridTemplateColumns: 'minmax(250px, .9fr) minmax(360px, 1.4fr)', gap: '1rem', alignItems: 'start' }}><section style={{ display: 'grid', gap: '.6rem' }}>{leads.length === 0 && <p style={{ color: '#6b7280' }}>Aucune demande reçue pour le moment.</p>}{leads.map(lead => <button key={lead.id} onClick={() => setSelected(lead)} style={{ textAlign: 'left', background: selected?.id === lead.id ? '#f0ebfa' : 'white', border: selected?.id === lead.id ? '2px solid #7652CA' : '1px solid #ead9a6', borderRadius: 10, padding: '.85rem', cursor: 'pointer' }}><strong>{lead.name}</strong><div style={{ fontSize: '.78rem', color: '#59565f' }}>{lead.travelType} · {statusLabels[lead.status] || lead.status}</div><div style={{ fontSize: '.7rem', color: '#a8a29e' }}>{new Date(lead.createdAt).toLocaleString('fr-FR')}</div></button>)}</section><section style={{ background: 'white', border: '1px solid #ead9a6', borderRadius: 12, padding: '1.25rem', minHeight: 300 }}>{!selected ? <p style={{ color: '#6b7280' }}>Sélectionne une demande pour voir le ticket.</p> : <><h2 style={{ margin: 0 }}>{selected.name}</h2><p style={{ color: '#59565f' }}>{selected.email}{selected.phone ? ` · ${selected.phone}` : ''}</p><div style={{ display: 'grid', gap: '.35rem', margin: '1rem 0' }}>{Object.entries(selected.qualification || {}).map(([key, value]) => <div key={key} style={{ fontSize: '.85rem' }}><strong>{key} :</strong> {String(value)}</div>)}</div><label style={{ display: 'block', fontWeight: 700, fontSize: '.8rem' }}>Statut<select value={selected.status} onChange={event => change(selected.id, event.target.value)} style={{ display: 'block', width: '100%', padding: '.55rem', marginTop: '.35rem' }}>{statuses.map(status => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></label><h3 style={{ marginBottom: '.4rem' }}>Historique du ticket</h3><div style={{ display: 'grid', gap: '.35rem', marginBottom: '1rem' }}>{(selected.events || []).map(event => <div key={event.id} style={{ fontSize: '.78rem', color: '#59565f' }}>{new Date(event.createdAt).toLocaleString('fr-FR')} · {event.actor} · {event.event}</div>)}</div><h3 style={{ marginBottom: '.4rem' }}>Message prêt à envoyer à l’agence</h3><textarea value={template} readOnly rows={12} style={{ width: '100%', boxSizing: 'border-box', padding: '.75rem', border: '1px solid #ddd6fe', borderRadius: 8, fontFamily: 'inherit' }} /><a href={`mailto:?subject=${encodeURIComponent(`Demande ${selected.travelType} - ${selected.name}`)}&body=${encodeURIComponent(template)}`} style={{ display: 'inline-block', marginTop: '.65rem', background: '#7652CA', color: 'white', borderRadius: 8, padding: '.65rem 1rem', fontWeight: 700, textDecoration: 'none' }}>Ouvrir le mail prérempli</a></>}</section></div>;
}
