'use client';
import { useEffect, useMemo, useState } from 'react';
import LeadMessages from '@/components/admin/LeadMessages';

type Event = { id: string; event: string; actor: string; createdAt: string; payload?: Record<string, unknown> | null };
type Partner = { contactAllowed: boolean; id: string; name: string; email: string; phone?: string | null; status: string };
type Lead = { consentFollowUp: boolean; id: string; ticketReference?: string | null; name: string; email: string; phone?: string | null; travelType: string; offerId: string | null; partnerId: string | null; status: string; qualification?: Record<string, unknown> | null; createdAt: string; updatedAt?: string; events?: Event[] };
const statuses = ['new', 'qualified', 'assigned', 'accepted', 'quoted', 'won', 'lost', 'expired'];
const labels: Record<string, string> = { new: 'Nouveau', qualified: 'Qualifié', assigned: 'Attribué', accepted: 'Pris en charge', quoted: 'Devis demandé', won: 'Finalisé', lost: 'Sans suite', expired: 'Archivé' };
const colors: Record<string, string> = { new: '#16a34a', qualified: '#7652CA', assigned: '#2563eb', accepted: '#0891b2', quoted: '#d97706', won: '#15803d', lost: '#6b7280', expired: '#9ca3af' };
function reference(lead: Lead) { return lead.ticketReference || `AW-${new Date(lead.createdAt).getFullYear()}-${lead.id.slice(0, 6).toUpperCase()}`; }
function age(date: string) { const hours = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 3600000)); return hours < 1 ? 'moins d’une heure' : hours < 24 ? `${hours} h` : `${Math.floor(hours / 24)} j ${hours % 24} h`; }
function val(q: Record<string, unknown>, ...keys: string[]) { const value = keys.map(k => q[k]).find(v => v !== undefined && v !== null && String(v).trim()); return value === undefined ? 'Non précisé' : String(value); }

export default function LeadsClient() {
 const [leads, setLeads] = useState<Lead[]>([]), [partners, setPartners] = useState<Partner[]>([]), [selected, setSelected] = useState<Lead | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [filter, setFilter] = useState('all'), [query, setQuery] = useState('');
 async function load() { setLoading(true); setError(''); try { const r = await fetch('/api/admin/leads', { cache: 'no-store', signal: AbortSignal.timeout(8000) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || 'Impossible de charger les demandes.'); const next = (d.leads || []) as Lead[]; setLeads(next); setPartners((d.partners || []) as Partner[]); setSelected(s => s ? next.find(x => x.id === s.id) || null : next[0] || null); } catch (e) { setError(e instanceof Error ? e.message : 'Impossible de charger les demandes.'); } finally { setLoading(false); } }
 useEffect(() => { load(); }, []);
 async function action(body: Record<string, string>) { const r = await fetch('/api/admin/leads', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, updatedAt: selected?.updatedAt }) }); if (!r.ok) { const d = await r.json().catch(() => ({})); setError(d.error || 'Action impossible.'); return; } await load(); }
 const filtered = useMemo(() => leads.filter(lead => { const q = query.toLowerCase(); return (filter === 'all' || lead.status === filter) && (!q || `${reference(lead)} ${lead.name} ${lead.email} ${lead.travelType}`.toLowerCase().includes(q)); }), [leads, filter, query]);
 const partner = selected?.partnerId ? partners.find(p => p.id === selected.partnerId && p.contactAllowed) : undefined;
 const message = useMemo(() => { if (!selected) return ''; const q = selected.qualification || {}; return `Bonjour,\n\nNous vous contactons au sujet de la demande Al-Wasil ${reference(selected)} concernant un ${selected.travelType}.\n\nBudget : ${val(q, 'budget')}\nDépart : ${val(q, 'depart', 'ville_depart')}\nVoyageurs : ${val(q, 'voyageurs', 'nombre', 'personnes')}\n\nMerci de nous proposer une formule adaptée et de confirmer les conditions.\n\nCordialement,\nMégane - Al-Wasil`; }, [selected]);
 if (loading) return <p>Chargement des demandes…</p>;
 if (error && !leads.length) return <div style={{ padding: '1rem', color: '#991b1b' }}><strong>{error}</strong><br /><button onClick={load}>Réessayer</button></div>;
 return <div>
  {error && <div style={{ padding: '.65rem 1rem', marginBottom: '1rem', color: '#991b1b', background: '#fee2e2', borderRadius: 10 }}>{error}</div>}
  <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: '1rem' }}>{[['all', 'Toutes'], ...statuses.map(s => [s, labels[s]])].map(([key, label]) => <button key={key} type="button" onClick={() => setFilter(key)} style={{ border: filter === key ? '2px solid #7652CA' : '1px solid #d8ccef', borderRadius: 999, background: filter === key ? '#7652CA' : 'white', color: filter === key ? 'white' : '#3f315f', padding: '.45rem .7rem', fontWeight: 700, fontSize: '.78rem' }}>{label} {key === 'all' ? leads.length : leads.filter(l => l.status === key).length}</button>)}</div>
  <input value={query} onChange={e => setQuery(e.target.value)} placeholder="Rechercher une référence, un client ou un voyage…" style={{ width: '100%', boxSizing: 'border-box', padding: '.8rem 1rem', border: '1px solid #d8ccef', borderRadius: 10, marginBottom: '1rem' }} />
  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,340px),1fr))', gap: '1rem', alignItems: 'start' }}>
   <section style={{ display: 'grid', gap: '.55rem', maxHeight: 700, overflowY: 'auto' }}>{!filtered.length && <p>Aucun ticket pour ce filtre.</p>}{filtered.map(lead => <button key={lead.id} onClick={() => setSelected(lead)} style={{ textAlign: 'left', background: selected?.id === lead.id ? '#f0ebfa' : 'white', border: selected?.id === lead.id ? '2px solid #7652CA' : '1px solid #ead9a6', borderRadius: 12, padding: '.85rem', cursor: 'pointer' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><strong>{reference(lead)}</strong><span style={{ color: colors[lead.status] || '#555', fontSize: '.75rem', fontWeight: 800 }}>● {labels[lead.status] || lead.status}</span></div><div style={{ marginTop: '.35rem', fontWeight: 700 }}>{lead.name}</div><div style={{ color: '#57534e', fontSize: '.84rem' }}>{lead.travelType}</div><small style={{ color: '#78716c' }}>Ouvert depuis {age(lead.createdAt)}</small></button>)}</section>
   <section style={{ background: 'white', border: '1px solid #ead9a6', borderRadius: 12, padding: '1.25rem' }}>{!selected ? <p>Sélectionne un ticket pour voir le détail.</p> : <>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'start' }}><div><small style={{ color: '#7652CA', fontWeight: 800 }}>{reference(selected)}</small><h2 style={{ margin: '.25rem 0' }}>{selected.travelType}</h2><small>Créé il y a {age(selected.createdAt)}</small></div><span style={{ color: colors[selected.status] || '#555', fontWeight: 800 }}>● {labels[selected.status]}</span></div>
    <hr style={{ border: 0, borderTop: '1px solid #eee', margin: '1rem 0' }} />
    <h3>Informations client</h3><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '.45rem', fontSize: '.9rem' }}><div><strong>Nom</strong><br />{selected.name}</div><div><strong>Voyageurs</strong><br />{val(selected.qualification || {}, 'voyageurs', 'nombre', 'personnes')}</div><div><strong>Email</strong><br /><a href={`mailto:${selected.email}`}>{selected.email}</a></div><div><strong>Téléphone</strong><br />{selected.phone ? <a href={`tel:${selected.phone}`}>{selected.phone}</a> : 'Non renseigné'}</div><div><strong>Budget</strong><br />{val(selected.qualification || {}, 'budget')}</div><div><strong>Départ</strong><br />{val(selected.qualification || {}, 'depart', 'ville_depart')}</div></div>
    <h3>Suivi interne</h3><label>Statut<select value={selected.status} onChange={e => action({ id: selected.id, status: e.target.value })} style={{ display: 'block', width: '100%', padding: '.6rem', marginTop: '.3rem' }}>{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label><label style={{ display: 'block', marginTop: '.8rem' }}>Agence attribuée<select value={selected.partnerId || ''} onChange={e => e.target.value && action({ id: selected.id, partnerId: e.target.value })} style={{ display: 'block', width: '100%', padding: '.6rem', marginTop: '.3rem' }}><option value="">Sélectionner une agence</option>{partners.filter(p => p.contactAllowed).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{partner ? <p style={{ fontSize: '.85rem' }}>Agence : <a href={`mailto:${partner.email}`}>{partner.email}</a>{partner.phone ? <> · <a href={`tel:${partner.phone}`}>{partner.phone}</a></> : null}</p> : selected.partnerId ? <p style={{ fontSize: '.85rem', color: '#92400e', background: '#fef3c7', padding: '.55rem', borderRadius: 8 }}>Référence agence conservée : <strong>{selected.partnerId}</strong>. Coordonnées à compléter dans les partenaires.</p> : <p style={{ fontSize: '.85rem', color: '#92400e' }}>Aucune agence n’est encore rattachée à ce ticket.</p>}
    <LeadMessages id={selected.id} partnerAllowed={!!partner} active={selected.status !== 'expired' && selected.consentFollowUp} />
    <h3>Historique</h3><div style={{ display: 'grid', gap: '.4rem', fontSize: '.8rem' }}>{(selected.events || []).map(e => <div key={e.id} style={{ display: 'flex', justifyContent: 'space-between', gap: '.5rem' }}><span>{new Date(e.createdAt).toLocaleString('fr-FR')} · {e.actor} · {e.event}</span>{e.event === 'status_changed' && e.payload?.previousStatus ? <button type="button" onClick={() => action({ rollbackEventId: e.id })}>Annuler</button> : null}</div>)}</div>
   </>}</section>
  </div>
 </div>;
}
