CREATE TYPE "public"."lead_status" AS ENUM('new', 'qualified', 'assigned', 'accepted', 'quoted', 'won', 'lost', 'expired');
CREATE TYPE "public"."assignment_status" AS ENUM('proposed', 'accepted', 'refused', 'expired');
CREATE TYPE "public"."commission_status" AS ENUM('pending', 'due', 'paid', 'disputed');
CREATE TABLE "partners" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "name" text NOT NULL, "email" text NOT NULL, "phone" text, "status" text NOT NULL DEFAULT 'pending', "commission_rate" real NOT NULL DEFAULT 0.04, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "offers" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "partner_id" uuid NOT NULL REFERENCES "partners"("id"), "type" text NOT NULL, "title" text NOT NULL, "price" integer, "valid_from" timestamptz, "valid_until" timestamptz, "status" text NOT NULL DEFAULT 'draft', "metadata" jsonb DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "leads" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "offer_id" text, "partner_id" text, "status" "lead_status" NOT NULL DEFAULT 'new', "name" text NOT NULL, "email" text NOT NULL, "phone" text, "travel_type" text NOT NULL, "qualification" jsonb DEFAULT '{}'::jsonb, "source" text, "utm" jsonb DEFAULT '{}'::jsonb, "consent_follow_up" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "lead_assignments" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "lead_id" uuid NOT NULL REFERENCES "leads"("id"), "offer_id" uuid REFERENCES "offers"("id"), "partner_id" uuid NOT NULL REFERENCES "partners"("id"), "status" "assignment_status" NOT NULL DEFAULT 'proposed', "expires_at" timestamptz, "responded_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "lead_events" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "lead_id" uuid NOT NULL REFERENCES "leads"("id"), "event" text NOT NULL, "actor" text NOT NULL DEFAULT 'system', "payload" jsonb DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "commissions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "lead_id" uuid NOT NULL REFERENCES "leads"("id"), "partner_id" uuid NOT NULL REFERENCES "partners"("id"), "amount" integer, "rate" real, "status" "commission_status" NOT NULL DEFAULT 'pending', "created_at" timestamptz NOT NULL DEFAULT now());
