'use client';
import { useEffect, useState } from 'react';
import { History, RotateCcw } from 'lucide-react';

type Entry = { id: string; itemId: string; title?: string | null; category?: string | null; action: string; actor: string; actedAt: string; previousStatus?: string | null; newStatus?: string | null; currentStatus?: string | null };
const labels: Record<string, string> = { approved: 'En ligne', pending: 'À vérifier', rejected: 'Rejetée', expired: 'Archivée' };
const actions: Record<string, string> = { approved: 'Validation', rejected: 'Rejet', archived: 'Archivage', edited: 'Modification', deleted: 'Suppression', reverification_requested: 'Nouvelle vérification' };

export default function HistoriqueClient() {
 const [rows, setRows] = useState<Entry[]>([]); const [loading, setLoading] = useState(true);
 async function load() { setLoading(true); const response = await fetch('/api/admin/historique', { cache: 'no-store' }); const data = await response.json(); setRows(data.history || []); setLoading(false); }
 useEffect(() => { load(); }, []);
 async function undo(id: string) { if (!window.confirm('Annuler cette action et restaurer le statut précédent ?')) return; const response = await fetch('/api/admin/historique', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ logId: id }) }); if (!response.ok) { const data = await response.json(); window.alert(data.error || 'Annulation impossible'); return; } await load(); }
 return <main style={{ minHeight: '100vh', background: 'linear-gradient(160deg,#f0ebfa,#faf9ff)', padding: '2rem 1rem' }}><div style={{ maxWidth: 1040, margin: '0 auto' }}><div style={{ display: 'flex', alignItems: 'center', gap: '.6rem', color: '#7652CA' }}><History size={20} /><h1 style={{ fontSize: '1.5rem', margin: 0 }}>Historique des actions</h1></div><p style={{ color: '#6b7280' }}>{rows.length} action{rows.length !== 1 ? 's' : ''} enregistrée{rows.length !== 1 ? 's' : ''} dans Neon</p>{loading ? <p>Chargement...</p> : !rows.length ? <div style={{ background: 'white', borderRadius: 16, padding: '4rem 2rem', textAlign: 'center', color: '#9ca3af' }}>Aucune action enregistrée.</div> : <div style={{ display: 'grid', gap: 10 }}>{rows.map(row => <article key={row.id} style={{ background: 'white', border: '1px solid #e2d7f5', borderLeft: `6px solid ${row.action === 'approved' ? '#16a34a' : row.action === 'rejected' ? '#dc2626' : '#7652CA'}`, borderRadius: 12, padding: '1rem', display: 'flex', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}><div><strong>{row.title || row.itemId}</strong><div style={{ color: '#6b7280', fontSize: 13 }}>{actions[row.action] || row.action} · {row.category || ' - '} · {new Date(row.actedAt).toLocaleString('fr-FR')}</div><div style={{ fontSize: 13, marginTop: 6 }}>Par <strong>{row.actor}</strong>{row.previousStatus && row.newStatus ? ` · ${labels[row.previousStatus] || row.previousStatus} → ${labels[row.newStatus] || row.newStatus}` : ''}</div></div>{row.previousStatus && row.currentStatus !== row.previousStatus && <button onClick={() => undo(row.id)} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, border: '1px solid #7652CA', background: 'white', color: '#7652CA', borderRadius: 8, padding: '.5rem .75rem', fontWeight: 700, cursor: 'pointer' }}><RotateCcw size={14} /> Annuler</button>}</article>)}</div>}</div></main>;
}
